// SPDX-License-Identifier: MIT

#include "x25519.h"
#include <string.h>
#include "psa/crypto.h"

#define CURVE_BITS 255

// PSA reports Montgomery public keys as the bare u-coordinate, little-endian,
// which is the same encoding the wire uses on both networks.
#define EXPORTED_PUBLIC_LEN X25519_KEY_LEN

static bool import_scalar(const uint8_t scalar[X25519_KEY_LEN], psa_key_usage_t usage, psa_key_id_t* out_id) {
    psa_key_attributes_t attributes = PSA_KEY_ATTRIBUTES_INIT;
    psa_set_key_usage_flags(&attributes, usage);
    psa_set_key_algorithm(&attributes, PSA_ALG_ECDH);
    psa_set_key_type(&attributes, PSA_KEY_TYPE_ECC_KEY_PAIR(PSA_ECC_FAMILY_MONTGOMERY));
    psa_set_key_bits(&attributes, CURVE_BITS);

    *out_id = PSA_KEY_ID_NULL;
    return psa_import_key(&attributes, scalar, X25519_KEY_LEN, out_id) == PSA_SUCCESS;
}

bool x25519_agree(uint8_t out[X25519_KEY_LEN], const uint8_t scalar[X25519_KEY_LEN],
                  const uint8_t peer_u[X25519_KEY_LEN]) {
    if (out == NULL || scalar == NULL || peer_u == NULL) return false;

    psa_key_id_t key_id;
    if (!import_scalar(scalar, PSA_KEY_USAGE_DERIVE, &key_id)) return false;

    size_t       len    = 0;
    psa_status_t status = psa_raw_key_agreement(PSA_ALG_ECDH, key_id, peer_u, X25519_KEY_LEN, out, X25519_KEY_LEN,
                                                &len);
    psa_destroy_key(key_id);

    if (status != PSA_SUCCESS || len != X25519_KEY_LEN) {
        memset(out, 0, X25519_KEY_LEN);
        return false;
    }

    // An all-zero result means the peer sent a low-order point and the "secret"
    // is one every attacker also knows. PSA rejects those, but checking costs
    // nothing and this is the one outcome that must never be used as a key.
    uint8_t accumulated = 0;
    for (size_t i = 0; i < X25519_KEY_LEN; i++) accumulated |= out[i];
    if (accumulated == 0) return false;

    return true;
}

bool x25519_public_from_private(uint8_t public_key[X25519_KEY_LEN], const uint8_t private_key[X25519_KEY_LEN]) {
    if (public_key == NULL || private_key == NULL) return false;

    psa_key_id_t key_id;
    if (!import_scalar(private_key, PSA_KEY_USAGE_EXPORT, &key_id)) return false;

    size_t       len    = 0;
    psa_status_t status = psa_export_public_key(key_id, public_key, EXPORTED_PUBLIC_LEN, &len);
    psa_destroy_key(key_id);

    return status == PSA_SUCCESS && len == EXPORTED_PUBLIC_LEN;
}

bool x25519_keypair(uint8_t public_key[X25519_KEY_LEN], uint8_t private_key[X25519_KEY_LEN]) {
    if (public_key == NULL || private_key == NULL) return false;

    // Generated by PSA rather than by filling random bytes ourselves, so the
    // clamping and any curve-specific rejection are the implementation's
    // problem rather than assumptions made here.
    psa_key_attributes_t attributes = PSA_KEY_ATTRIBUTES_INIT;
    psa_set_key_usage_flags(&attributes, PSA_KEY_USAGE_EXPORT | PSA_KEY_USAGE_DERIVE);
    psa_set_key_algorithm(&attributes, PSA_ALG_ECDH);
    psa_set_key_type(&attributes, PSA_KEY_TYPE_ECC_KEY_PAIR(PSA_ECC_FAMILY_MONTGOMERY));
    psa_set_key_bits(&attributes, CURVE_BITS);

    psa_key_id_t key_id = PSA_KEY_ID_NULL;
    if (psa_generate_key(&attributes, &key_id) != PSA_SUCCESS) return false;

    size_t private_len = 0;
    size_t public_len  = 0;
    bool   ok = psa_export_key(key_id, private_key, X25519_KEY_LEN, &private_len) == PSA_SUCCESS &&
              psa_export_public_key(key_id, public_key, EXPORTED_PUBLIC_LEN, &public_len) == PSA_SUCCESS;
    psa_destroy_key(key_id);

    if (!ok || private_len != X25519_KEY_LEN || public_len != EXPORTED_PUBLIC_LEN) {
        memset(private_key, 0, X25519_KEY_LEN);
        memset(public_key, 0, EXPORTED_PUBLIC_LEN);
        return false;
    }
    return true;
}

// --- self-test -----------------------------------------------------------

// RFC 7748 section 6.1.
static const uint8_t ALICE_PRIVATE[32] = {0x77, 0x07, 0x6d, 0x0a, 0x73, 0x18, 0xa5, 0x7d, 0x3c, 0x16, 0xc1,
                                          0x72, 0x51, 0xb2, 0x66, 0x45, 0xdf, 0x4c, 0x2f, 0x87, 0xeb, 0xc0,
                                          0x99, 0x2a, 0xb1, 0x77, 0xfb, 0xa5, 0x1d, 0xb9, 0x2c, 0x2a};
static const uint8_t ALICE_PUBLIC[32]  = {0x85, 0x20, 0xf0, 0x09, 0x89, 0x30, 0xa7, 0x54, 0x74, 0x8b, 0x7d,
                                          0xdc, 0xb4, 0x3e, 0xf7, 0x5a, 0x0d, 0xbf, 0x3a, 0x0d, 0x26, 0x38,
                                          0x1a, 0xf4, 0xeb, 0xa4, 0xa9, 0x8e, 0xaa, 0x9b, 0x4e, 0x6a};
static const uint8_t BOB_PRIVATE[32]   = {0x5d, 0xab, 0x08, 0x7e, 0x62, 0x4a, 0x8a, 0x4b, 0x79, 0xe1, 0x7f,
                                          0x8b, 0x83, 0x80, 0x0e, 0xe6, 0x6f, 0x3b, 0xb1, 0x29, 0x26, 0x18,
                                          0xb6, 0xfd, 0x1c, 0x2f, 0x8b, 0x27, 0xff, 0x88, 0xe0, 0xeb};
static const uint8_t BOB_PUBLIC[32]    = {0xde, 0x9e, 0xdb, 0x7d, 0x7b, 0x7d, 0xc1, 0xb4, 0xd3, 0x5b, 0x61,
                                          0xc2, 0xec, 0xe4, 0x35, 0x37, 0x3f, 0x83, 0x43, 0xc8, 0x5b, 0x78,
                                          0x67, 0x4d, 0xad, 0xfc, 0x7e, 0x14, 0x6f, 0x88, 0x2b, 0x4f};
static const uint8_t SHARED[32]        = {0x4a, 0x5d, 0x9d, 0x5b, 0xa4, 0xce, 0x2d, 0xe1, 0x72, 0x8e, 0x3b,
                                          0xf4, 0x80, 0x35, 0x0f, 0x25, 0xe0, 0x7e, 0x21, 0xc9, 0x47, 0xd1,
                                          0x9e, 0x33, 0x76, 0xf0, 0x9b, 0x3c, 0x1e, 0x16, 0x17, 0x42};

bool x25519_selftest(void) {
    uint8_t derived[32];
    if (!x25519_public_from_private(derived, ALICE_PRIVATE) || memcmp(derived, ALICE_PUBLIC, 32) != 0) return false;
    if (!x25519_public_from_private(derived, BOB_PRIVATE) || memcmp(derived, BOB_PUBLIC, 32) != 0) return false;

    // Both directions, because a byte-order error can produce a secret that is
    // self-consistent on one side and wrong on the wire.
    uint8_t secret[32];
    if (!x25519_agree(secret, ALICE_PRIVATE, BOB_PUBLIC) || memcmp(secret, SHARED, 32) != 0) return false;
    if (!x25519_agree(secret, BOB_PRIVATE, ALICE_PUBLIC) || memcmp(secret, SHARED, 32) != 0) return false;

    return true;
}
